name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      env:
        ENC_KEY: ${{ secrets.ENC_KEY }}
      run: cargo build --verbose
    - name: Run tests
      env:
        ENC_KEY: ${{ secrets.ENC_KEY }}
      run: cargo test --verbose
